name: GCN

params:
  photo:
    norm: true 
    loop: true  
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.5
      drop_input: false
      batch_norm: true  
      residual: false
      gnn_norm: true
      gnn_self_loops: false
    optim: adam
    lr: 0.005
    wd: 0.00001
    epochs: 1000

  wikics:
    norm: true 
    loop: true  
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.5
      drop_input: false 
      batch_norm: true
      residual: false
      gnn_norm: true
      gnn_self_loops: false 
    optim: adam
    lr: 0.05
    wd: 0.00001
    epochs: 1000

  squirrel:
    norm: true 
    loop: true  
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 128 
      dropout: 0.5
      drop_input: false
      batch_norm: true
      residual: false
      gnn_norm: true 
      gnn_self_loops: false  
    optim: adam
    lr: 0.05
    wd: 0. 
    epochs: 1000

  reddit2:
    norm: false 
    loop: false 
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.5
      drop_input: false
      batch_norm: true
      residual: false
      gnn_norm: false
      gnn_self_loops: false
    optim: adam
    lr: 0.01
    wd: 0.0
    epochs: 1000
  
  proteins:
    norm: true 
    loop: true  
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.5
      batch_norm: true
      residual: false
      gnn_norm: false
      gnn_self_loops: false 
    optim: adam
    adjust_lr: false
    use_labels: false
    lr: 0.01
    wd: 0.00001
    epochs: 1000
    log_steps: 1