name: GCN2

params:
  photo:
    loop: true
    norm: true
    arch_name: GCN2
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.
      drop_input: false
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
      gnn_norm: true 
      gnn_self_loops: false  
    optim: adam
    lr: 0.005
    wd: 0.00001
    epochs: 800

  wikics:
    loop: true
    norm: true
    arch_name: GCN2
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.3
      drop_input: true 
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
      gnn_norm: true 
      gnn_self_loops: false  
    optim: adam
    lr: 0.01
    wd: 0.00005
    epochs: 800 

  squirrel:
    loop: true
    norm: true
    arch_name: GCN2
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.5
      drop_input: true
      batch_norm: false
      residual: false
      shared_weights: false
      alpha: 0.
      theta: 1.0
      gnn_norm: true 
      gnn_self_loops: false  
    optim: adam
    lr: 0.05
    wd: 0.0
    epochs: 800

  reddit2:
    loop: false
    norm: false
    arch_name: GCN2
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.
      drop_input: true
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
      gnn_norm: false 
      gnn_self_loops: false  
    optim: adam
    lr: 0.01
    wd: 0.0
    epochs: 800

  proteins:
    loop: true
    norm: true  
    arch_name: GCN2
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.5
      drop_input: false
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.2
      theta: 0.5
      gnn_norm: false
      gnn_self_loops: false  
    optim: adam
    lr: 0.01
    wd: 0.00001
    epochs: 1000
    adjust_lr: false
    use_labels: false